### ISSUE TITLE
Add support for S3 compatible storage providers

### ISSUE THREAD

**Issue by LaurensVanAcker** [adebayohountondji/strapi-plugin-backup#1]
Hello, is it possible to include the endpoint configuration option to enable other S3 compatible storage providers such as Backblaze?
This was implemented in the S3 media storage plugin, which can be found at https://github.com/strapi/strapi/blob/3b504a5284f4e0eeaec73af89fc7c1604a953214/packages/providers/upload-aws-s3/src/index.ts#L39.

You can also find documentation regarding this feature at https://market.strapi.io/providers/@strapi-provider-upload-aws-s3.

**Comment by adebayohountondji** [comment]
Hello @LaurensVanAcker,

I am pleased to inform you that the functionality you requested has been successfully added to the latest version of the plugin, v1.0.0-rc.1, now available on Github and NPM.

Thank you again for your suggestion and your interest in this project.
