### ISSUE TITLE
Configuration for backup

### ISSUE THREAD

**Issue by Yujink0624** [adebayohountondji/strapi-plugin-backup#11]
Hi,

I am using Strapi cloud, and would like to use this plug-in to achieve daily backup. 

Questions : 
1. `databaseDriver`: `env('DATABASE_CLIENT')` : What should be the value for DATABASE_CLIENT? I believe we are using PostgreSQL.
2. `pgDumpExecutable` : How to get this path? The strapi is running in cloud, so I am not sure where to grab this path.

Any response will be appreciated!

**Comment by adebayohountondji** [comment]
Hello @Yujink0624 ,

1. The value of `DATABASE_CLIENT` must be `postgres` if you are using PostgreSQL.
2. You must contact your cloud provider to get the `pgDumpExecutable` path.

Thank you for your interest in this project

All the best
