### ISSUE TITLE
Error with strapi-plugin-backup using SQLite database on local project

### ISSUE THREAD

**Issue by DhanukaSonicLabs** [adebayohountondji/strapi-plugin-backup#3]
I have tried to use **sqlite** default db on strapi local project before deploy to the cloud and also the **strapi-plugin-backup** strapi plugin for backup my DB to aws s3 bucket. The issue is, **_what is the suitable value for "sqlite3Executable" ??_**. 

I have tried so many types of values as path and file names. But its getting me error like this.  "is not recognized as an internal or external command".

When we use default database as sqlite for the newly created strapi project its creating a db in file we configure as data.db file inside .tmp directory. I just given that path to the backup plugin and its not working. And also in the document and the github repository descriptions also have no any explanation for this and could you please send me some solution for this one.

This is my strapi dtabase.js file
```
const path = require("path");

module.exports = ({ env }) => {
  const client = env("DATABASE_CLIENT", "sqlite");

  const connections = {
    sqlite: {
      connection: {
        filename: path.join(
          __dirname,
          "..",
          env("DATABASE_FILENAME", ".tmp/data.db")
        ),
      },
      useNullAsDefault: true,
    },
  };

  return {
    connection: {
      client,
      ...connections[client],
      acquireConnectionTimeout: env.int("DATABASE_CONNECTION_TIMEOUT", 60000),
    },
  };
};
```

This is the code I have used for backup plugin configuration 
```
const path = require("path");

module.exports = ({ env }) => ({
  backup: {
    enabled: true,
    config: {
      cronSchedule: "* 9-17 * * *",
      storageService: "aws-s3",
      awsAccessKeyId: "*******************",
      awsSecretAccessKey: "*******************",
      awsRegion: "*******************",
      awsS3Bucket: "*******************",
      databaseDriver: env("DATABASE_CLIENT"),
      sqlite3Executable: path.resolve(__dirname, "..", ".tmp"),
      allowCleanup: true,
      timeToKeepBackupsInSeconds: 172800,
      cleanupCronSchedule: "0 9 * * *",
    },
  },
});
```

**Comment by adebayohountondji** [comment]
Hello @DhanukaSonicLabs,

`sqlite3Executable` must be the absolute path to your command line shell for SQLite. You can find more information about sqlite3 on the following link [https://www.sqlite.org/cli.html](https://www.sqlite.org/cli.html).

**Comment by DhanukaSonicLabs** [comment]
@adebayohountondji  Thanks for the reply.

 I used `Strapi Cloud` with default Strapi project deployment using SQLite database. Is there any shell for SQLite in the default path ?? In that path there is only creating **data.db** file and its not be able to execute the SQLite shell commands.

**Comment by adebayohountondji** [comment]
@DhanukaSonicLabs 

If you have access to your `strapi` instance running on Strapi Cloud, you should run a `which sqlite3` to try to find an absolute path to the `sqlite3` executable. If `sqlite3` is not available on the machine running your strapi app , try to ask your provider if they can add this to you or add it yourself if possible.

If you really can’t find a solution I can upgrade the plugin to directly backup your database file without trying to export Sql with Sqlite3 if `sqlite3Executable` is not defined.
