### ISSUE TITLE
Add support for Node 20

### ISSUE THREAD

**Issue by brinca** [adebayohountondji/strapi-plugin-backup#6]
When installing the strapi backup plugin, the following error pops up:
```
error strapi-plugin-backup@1.1.2: The engine "node" is incompatible with this module. Expected version ">=14.19.1 <=18.x.x". Got "20.9.0"
error Found incompatible module.
```

Since Node 20 entered LTS in October, I think it's safe to include in a release.

**Comment by kubarazny** [comment]
hello, any update? current version of node.js is 21.7.1 but this plugin doesn't have support for 20.11.1 :(

**Comment by adebayohountondji** [comment]
Hello @brinca @kubarazny 

I’ll take care of it this week
