### ISSUE TITLE
Question: Best practice for restoring backup?

### ISSUE THREAD

**Issue by Sparo** [adebayohountondji/strapi-plugin-backup#7]
Hi,

Tnx for the plugin! 

I have a question - is there some best practice how to restore backup?

All the best

**Comment by adebayohountondji** [comment]
Hi

No there is not really a good practice to restore dumps. You can do it on the command line with the client of your Sql driver or via a graphical interface offered by your provide to cloud for example

Thank you for your interest in this project

All the best
